#!/bin/bash

# Define colors
R="\033[31m"  # Red
G="\033[32m"  # Green
Y="\033[33m"  # Yellow
N="\033[0m"   # Reset

DATE=$(date)
TIMESTAMP=$(date +%F-%H-%M-%S)
LOGFILE="/Users/kethanav/Desktop/DevOps_2025/shellscript/$0-$TIMESTAMP.log"



# Example with green text
echo -e "Hello World! I am learning ${G}DevOps${N}, Shell Scripting." > $LOGFILE

# Example with multiple colors
echo -e "${R}Error:${N} Something went wrong"
echo -e "${Y}Warning:${N} Be careful"
echo -e "${G}Success:${N} Task completed"

# Print the date
echo -e "Today's date is: ${Y}$(date)${N}"

# Comments work normally with #
# This is a comment

